server:
  port: 8001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/toegeungil
    username: teddy6
    password: teddy6223

  jpa:
    hibernate:
      #DDL자동 생성
      #create: 기존 DDl을 제거하고 새로 생성한다.
      #update: 현재 DB DDL과 비교해서 변경사항만 수정한다.
      #none: 자동 생성 기능을 사용히지 않는다는 유효하지 않은 옵션 값.
      ddl-auto: create
    properties:
      hibernate:
        #SQL보기(실행하는 SQL을 콘솔에 출력한다)
        show_sql: true
        #SQL정렬해서 보기
        format_sql: true

