server:
  port: 8001

spring:
  application:
    name: application
  profiles:
    active: dev
    include: email
  config:
<<<<<<< HEAD
    import: optional:configserver:http://106.250.199.126:7777
=======
    import: optional:configserver:http://106.250.199.126:7777


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true
    web:
      resources:
        static-locations: classpath:/static/upload/



#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/toegeungil
#    username: teddy6
#    password: teddy6223

#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
>>>>>>> be8b780c161793dfe1bec5d34092c2ae6cbfe141
