#google
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: algoreatt@gmail.com
    password: zktxodpvbkrcgqvg
    properties:
      mail :
        smtp :
          enable : true
        auth : true


email :
  host: smtp.gmail.com
  port: 587
  username: algoreatt@gmail.com
  password: zktxodpvbkrcgqvg