Jwt:
  key: DF9279CB6FSD1AD6B6A6184A31E6BE37DB3818CC36871E26235DD67DCFE4041492

server:
  port: 8001
#
spring:
  application:
    name: application
  profiles:
    active: dev
  config:
    import: optional:configserver:http://222.112.124.237:7777

  error:
    include-exception: true # 오류 응답에 exception의 내용을 포함할지
    include-stacktrace: always # 오류 응답에 stacktrace 내용을 포함할 지 여부

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/toegeungil
#    username: teddy6
#    password: teddy6223
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true